version: '3.9'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - main/.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - main/.env
