# Generated by Django 4.0.2 on 2022-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                ("date", models.DateField(db_index=True)),
                ("channel", models.CharField(db_index=True, max_length=20)),
                ("country", models.CharField(db_index=True, max_length=2)),
                ("os", models.CharField(db_index=True, max_length=10)),
                ("impressions", models.PositiveIntegerField(blank=True, null=True)),
                ("clicks", models.PositiveIntegerField(blank=True, null=True)),
                ("installs", models.PositiveIntegerField(blank=True, null=True)),
                ("spend", models.FloatField(blank=True, null=True)),
                ("revenue", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
